//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ders4.IETTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IETTService.ibbSoap")]
    public interface ibbSoap {
        
        // CODEGEN: Generating message contract since element name hat_kodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DurakDetay_GYY", ReplyAction="*")]
        Ders4.IETTService.DurakDetay_GYYResponse DurakDetay_GYY(Ders4.IETTService.DurakDetay_GYYRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DurakDetay_GYY", ReplyAction="*")]
        System.Threading.Tasks.Task<Ders4.IETTService.DurakDetay_GYYResponse> DurakDetay_GYYAsync(Ders4.IETTService.DurakDetay_GYYRequest request);
        
        // CODEGEN: Generating message contract since element name hat_kodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HatServisi_GYY", ReplyAction="*")]
        Ders4.IETTService.HatServisi_GYYResponse HatServisi_GYY(Ders4.IETTService.HatServisi_GYYRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HatServisi_GYY", ReplyAction="*")]
        System.Threading.Tasks.Task<Ders4.IETTService.HatServisi_GYYResponse> HatServisi_GYYAsync(Ders4.IETTService.HatServisi_GYYRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DurakDetay_GYYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DurakDetay_GYY", Namespace="http://tempuri.org/", Order=0)]
        public Ders4.IETTService.DurakDetay_GYYRequestBody Body;
        
        public DurakDetay_GYYRequest() {
        }
        
        public DurakDetay_GYYRequest(Ders4.IETTService.DurakDetay_GYYRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DurakDetay_GYYRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hat_kodu;
        
        public DurakDetay_GYYRequestBody() {
        }
        
        public DurakDetay_GYYRequestBody(string hat_kodu) {
            this.hat_kodu = hat_kodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DurakDetay_GYYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DurakDetay_GYYResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ders4.IETTService.DurakDetay_GYYResponseBody Body;
        
        public DurakDetay_GYYResponse() {
        }
        
        public DurakDetay_GYYResponse(Ders4.IETTService.DurakDetay_GYYResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DurakDetay_GYYResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement DurakDetay_GYYResult;
        
        public DurakDetay_GYYResponseBody() {
        }
        
        public DurakDetay_GYYResponseBody(System.Xml.Linq.XElement DurakDetay_GYYResult) {
            this.DurakDetay_GYYResult = DurakDetay_GYYResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HatServisi_GYYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HatServisi_GYY", Namespace="http://tempuri.org/", Order=0)]
        public Ders4.IETTService.HatServisi_GYYRequestBody Body;
        
        public HatServisi_GYYRequest() {
        }
        
        public HatServisi_GYYRequest(Ders4.IETTService.HatServisi_GYYRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HatServisi_GYYRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hat_kodu;
        
        public HatServisi_GYYRequestBody() {
        }
        
        public HatServisi_GYYRequestBody(string hat_kodu) {
            this.hat_kodu = hat_kodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HatServisi_GYYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HatServisi_GYYResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ders4.IETTService.HatServisi_GYYResponseBody Body;
        
        public HatServisi_GYYResponse() {
        }
        
        public HatServisi_GYYResponse(Ders4.IETTService.HatServisi_GYYResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HatServisi_GYYResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement HatServisi_GYYResult;
        
        public HatServisi_GYYResponseBody() {
        }
        
        public HatServisi_GYYResponseBody(System.Xml.Linq.XElement HatServisi_GYYResult) {
            this.HatServisi_GYYResult = HatServisi_GYYResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ibbSoapChannel : Ders4.IETTService.ibbSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ibbSoapClient : System.ServiceModel.ClientBase<Ders4.IETTService.ibbSoap>, Ders4.IETTService.ibbSoap {
        
        public ibbSoapClient() {
        }
        
        public ibbSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ibbSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ibbSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ibbSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ders4.IETTService.DurakDetay_GYYResponse Ders4.IETTService.ibbSoap.DurakDetay_GYY(Ders4.IETTService.DurakDetay_GYYRequest request) {
            return base.Channel.DurakDetay_GYY(request);
        }
        
        public System.Xml.Linq.XElement DurakDetay_GYY(string hat_kodu) {
            Ders4.IETTService.DurakDetay_GYYRequest inValue = new Ders4.IETTService.DurakDetay_GYYRequest();
            inValue.Body = new Ders4.IETTService.DurakDetay_GYYRequestBody();
            inValue.Body.hat_kodu = hat_kodu;
            Ders4.IETTService.DurakDetay_GYYResponse retVal = ((Ders4.IETTService.ibbSoap)(this)).DurakDetay_GYY(inValue);
            return retVal.Body.DurakDetay_GYYResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ders4.IETTService.DurakDetay_GYYResponse> Ders4.IETTService.ibbSoap.DurakDetay_GYYAsync(Ders4.IETTService.DurakDetay_GYYRequest request) {
            return base.Channel.DurakDetay_GYYAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ders4.IETTService.DurakDetay_GYYResponse> DurakDetay_GYYAsync(string hat_kodu) {
            Ders4.IETTService.DurakDetay_GYYRequest inValue = new Ders4.IETTService.DurakDetay_GYYRequest();
            inValue.Body = new Ders4.IETTService.DurakDetay_GYYRequestBody();
            inValue.Body.hat_kodu = hat_kodu;
            return ((Ders4.IETTService.ibbSoap)(this)).DurakDetay_GYYAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ders4.IETTService.HatServisi_GYYResponse Ders4.IETTService.ibbSoap.HatServisi_GYY(Ders4.IETTService.HatServisi_GYYRequest request) {
            return base.Channel.HatServisi_GYY(request);
        }
        
        public System.Xml.Linq.XElement HatServisi_GYY(string hat_kodu) {
            Ders4.IETTService.HatServisi_GYYRequest inValue = new Ders4.IETTService.HatServisi_GYYRequest();
            inValue.Body = new Ders4.IETTService.HatServisi_GYYRequestBody();
            inValue.Body.hat_kodu = hat_kodu;
            Ders4.IETTService.HatServisi_GYYResponse retVal = ((Ders4.IETTService.ibbSoap)(this)).HatServisi_GYY(inValue);
            return retVal.Body.HatServisi_GYYResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ders4.IETTService.HatServisi_GYYResponse> Ders4.IETTService.ibbSoap.HatServisi_GYYAsync(Ders4.IETTService.HatServisi_GYYRequest request) {
            return base.Channel.HatServisi_GYYAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ders4.IETTService.HatServisi_GYYResponse> HatServisi_GYYAsync(string hat_kodu) {
            Ders4.IETTService.HatServisi_GYYRequest inValue = new Ders4.IETTService.HatServisi_GYYRequest();
            inValue.Body = new Ders4.IETTService.HatServisi_GYYRequestBody();
            inValue.Body.hat_kodu = hat_kodu;
            return ((Ders4.IETTService.ibbSoap)(this)).HatServisi_GYYAsync(inValue);
        }
    }
}
